config/routes.rb
Rails.application.routes.draw do
  get 'tops/index'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
    post 'users/guest_farmer_nil_sign_in', to: 'users/sessions#guest_farmer_nil_sign_in'
    post 'users/guest_farmer_present_sign_in', to: 'users/sessions#guest_farmer_present_sign_in'
    post 'users/guest_general_nil_sign_in', to: 'users/sessions#guest_general_nil_sign_in'
    post 'users/guest_general_present_sign_in', to: 'users/sessions#guest_general_present_sign_in'
  end

  root 'tops#index'
  resources :tops, only: [:index]
  resources :users, only: [:show, :index]
  resources :relationships, only: [:create, :destroy]
  resources :users, only: [:show] do
    get "follows", on: :member
  end

  resources :generals, only: [:new, :create, :show, :edit, :update]
  resources :farmers, only: [:index, :new, :create, :show, :edit, :update] do
    get "overview", on: :member
  end
  resources :posts
  resources :experiences do
    resources :schedules, only: [:create, :edit, :update, :destroy]
  end
  resources :conversations do
    resources :messages
  end
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/tops/index.html.erb
<div class="container top-container">
  <h1 class="text-center mt-5 mb-4">農家さんと地元住民をつなぐアプリ</br>「Farm Link」</h1>
  <p>
    このアプリは、地元住民と農家を繋ぐための農業体験アプリです。</br>
    地方農業においては、労働力不足や地域コミュニティの希薄化という問題が深刻化しており、これらの課題を解決するために開発しました。
    このアプリでは、農家の作業負担を軽減すると同時に、地元住民が労働力不足に悩む農家と手軽につながり、農業体験を通じて農業に親しむ機会を提供することで、
    農業に興味を持つ人を増やし、地域コミュニティを活性化することを目的としています。
  </p>
  <div class="text-center mt-5"> 
    <% if user_signed_in? %>
      <%= link_to "農家を探す", farmers_path, class: "btn btn-secondary btn-lg" %>
    <% else %>
      <%= link_to "今すぐ始める", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    <% end %>
  </div>
  
  <h2 class="text-center mt-5 mb-4 style="font-weight: bold">機能一覧</h2>
  <ol>
  <div class="mb-3">
    <li>ユーザー認証機能
      <p>ユーザー登録、ログイン、ログアウト機能が提供されています。ゲストユーザーは、農家を探す画面から農家情報の検索・閲覧のみが可能です。登録時には、農家か一般ユーザーを選択し、登録後に選択された各プロフィール画面に遷移します。</p>
    </li>
  </div>
  <div class="mb-3">
    <li>農家プロフィール登録機能
      <p>ユーザー登録後すぐ、または後からプロフィール登録をすることができます。登録することで体験情報の登録や日々の投稿が可能になります。また、一般ユーザーや他の農家とメッセージやフォローができるようになります。</p>
    </li>
  </div>
  <div class="mb-3">
    <li>一般ユーザープロフィール登録機能
      <p>ユーザー登録後すぐ、または後からプロフィール登録をすることができます。登録することで農家とメッセージやフォローができるようになります。</p>
    </li>
  </div>
  <div class="mb-3">
    <li>検索機能
      <p>全ユーザーはキーワード、エリア、Googleマップで検索ができ、地元の農家や興味のある農作物を生産している農家を探すことができます。</p>
    </li>
  </div>
  <div class="mb-3">
    <li>体験情報登録機能
      <p>農家は、畑・水田・果樹園などの農地カテゴリごとに体験情報を登録できます。一般ユーザーは、興味のある体験情報を知ることができ、また気軽に農家を訪れることができます。</p>
    </li>
  </div>
  <div class="mb-3">
    <li>カレンダー機能
      <p>農家は農業体験の日程をカレンダーに登録することができます。一般ユーザーは、カレンダーから農業体験の日付を確認でき、自分のスケジュールに合わせて参加できる農業体験を見つけることができます。</p>
    </li>
  </div>
  <div class="mb-3">
    <li>投稿機能
      <p>農家は日々の日常を投稿することができます。一般ユーザーは、農家についてより深く知ることができ、興味を持つ農家を見つけるきっかけになります。</p>
    </li>
  </div>
  <div class="mb-3">
    <li>メッセージ機能
      <p>メッセージ機能により、農家と一般ユーザーは直接やり取りが可能です。そのため、質問や予約などをスムーズに行うことができます。</p>
    </li>
  </div>
  <div class="mb-3">
    <li>フォロー機能
      <p>一般ユーザーと農家がフォローすることができます。一般ユーザーは、農家の情報や投稿を追うことができ、興味を持つ農家を見つけるきっかけになります。農家も一般ユーザーをフォローすることで、地元住民とのつながりを築くことができ、コミュニティの活性化につながります。</p>
    </li>
  </div>
  </ol>

  <% unless user_signed_in? %>
    <div class="text-center mt-5">
      <%= link_to "ゲスト（ログインなし）", root_path, class: "btn btn-secondary me-2" %>
      <%= link_to "ゲストログイン（管理者)", users_guest_admin_sign_in_path, method: :post, class: "btn btn-secondary me-2" %>
    </div>
    <div class="text-center mt-5">
      <%= link_to "ゲストログイン（農家/プロフィール登録なし）", users_guest_farmer_nil_sign_in_path, method: :post, class: "btn btn-secondary me-2" %>
      <%= link_to "ゲストログイン（農家/プロフィール登録あり）", users_guest_farmer_present_sign_in_path, method: :post, class: "btn btn-secondary me-2" %>
    </div>
    <div class="text-center mt-5">
      <%= link_to "ゲストログイン（一般の方/プロフィール登録なし）", users_guest_general_nil_sign_in_path, method: :post, class: "btn btn-secondary me-2" %>
      <%= link_to "ゲストログイン（一般の方/プロフィール登録あり）", users_guest_general_present_sign_in_path, method: :post, class: "btn btn-secondary me-2" %>
    </div>
  <% end %>
</div>