config/routes.rb
Rails.application.routes.draw do
  get 'tops/index'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
    post 'users/guest_farmer_nil_sign_in', to: 'users/sessions#guest_farmer_nil_sign_in'
    post 'users/guest_farmer_present_sign_in', to: 'users/sessions#guest_farmer_present_sign_in'
    post 'users/guest_general_nil_sign_in', to: 'users/sessions#guest_general_nil_sign_in'
    post 'users/guest_general_present_sign_in', to: 'users/sessions#guest_general_present_sign_in'
  end

  root 'tops#index'
  resources :tops, only: [:index]
  resources :users, only: [:show, :index]
  resources :relationships, only: [:create, :destroy]
  resources :users, only: [:show] do
    get "follows", on: :member
  end

  resources :generals, only: [:new, :create, :show, :edit, :update]
  resources :farmers, only: [:index, :new, :create, :show, :edit, :update] do
    get "overview", on: :member
  end
  resources :posts
  resources :experiences do
    resources :schedules, only: [:create, :edit, :update, :destroy]
  end
  resources :conversations do
    resources :messages
  end
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :farmer
  has_many :experience_plots, dependent: :destroy
  has_many :schedules, dependent: :destroy
  has_many :plots, through: :experience_plots
  has_many_attached :images

  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true
  validate :validate_images
  validate :must_have_at_least_one_plot

  scope :created_at_sorted, -> { order(created_at: :desc) }

  private

  def validate_images
    if images.attached? && images.length > 4
      errors.add(:images, 'は最大4枚までアップロードできます')
    end
  end

  def must_have_at_least_one_plot
    if plot_ids.empty?
      errors.add(:base, "農地カテゴリを選択してください")
    end
  end
end

app/models/farmer.rb
class Farmer < ApplicationRecord
  attr_accessor :skip_plot_validation
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
  belongs_to :user
  has_one_attached :image
  has_many :posts, dependent: :destroy
  has_many :experiences, dependent: :destroy
  has_many :plots, dependent: :destroy
  accepts_nested_attributes_for :plots, allow_destroy: true, reject_if: :all_blank
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :name, presence: true, length: { maximum: 100 }
  validates :prefecture_id, presence: true
  validates :address, presence: true, length: { maximum: 255 }
  validates :station, presence: true, length: { maximum: 255 }
  validates :product, presence: true, length: { maximum: 255 }
  validates :website, length: { maximum: 255 }, format: { with: /\Ahttps?:\/\/[\S]+\z/, allow_blank: true }
  validate :validate_plot_presence

  scope :created_at_sorted, -> { order(created_at: :desc) }

  private
  
  def self.ransackable_attributes(auth_object = nil)
    ["address", "name", "product", "profile", "prefecture_id", "station"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end

  def validate_plot_presence
    return if skip_plot_validation
    valid_plots = plots.reject(&:marked_for_destruction?) # 削除される予定のプロットを除外し、残りのプロットを代入
    if valid_plots.empty? || valid_plots.all? { |plot| plot.name.blank? }
      errors.add(:base, "農地カテゴリを入力してください")
    end
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  load_and_authorize_resource
  before_action :set_experience, only: [:show, :edit, :update, :destroy]
  
  def index
    @experiences = current_user.farmer.experiences.includes(:plots).created_at_sorted
  end

  def show
    @plots = @experience.plots
  end

  def new
    @experience = Experience.new
    @plots = current_user.farmer.plots
  end

  def create
    @experience = current_user.farmer.experiences.build(experience_params)
    if @experience.save
      redirect_to @experience, notice: "体験情報が保存されました。次は体験スケジュールを入れてください！"
    else
      @plots = current_user.farmer.plots
      render :new
    end
  end

  def edit
    @plots = current_user.farmer.plots
    @schedules = @experience.schedules
  end

  def update
    if @experience.update(experience_params)
      redirect_to experience_path(@experience), notice: "体験情報が更新されました。"
    else
      render :edit
    end
  end

  def destroy
    @experience.destroy
    redirect_to experiences_url, notice: "体験情報が削除されました。"
  end

  
  private

  def experience_params
    params.require(:experience).permit(:title, :content, images: [], plot_ids: [])
  end

  def set_experience
    @experience = Experience.find(params[:id])
  end
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_form.html.erb
<%= form_with(model: experience, local: true) do |f| %>
  <% if experience.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% experience.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :plot_ids, class: "form-label" %>
    <span class="badge bg-danger">必須</span>
    <div class="d-flex">
      <%= f.collection_check_boxes :plot_ids, @plots, :id, :name do |b| %>
        <div class="form-check form-check-inline">
          <%= b.check_box(class: "form-check-input") %>
          <%= b.label(class: "form-check-label") %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="mb-3">
    <%= f.label :title, class: "form-label"%>
    <span class="badge bg-danger">必須</span>
    <%= f.text_field :title, class: "form-control#{" is-invalid" if experience.errors.include?(:title)}", placeholder: "タイトルを入力してください" %>
  </div>

  <div class="mb-3">
    <%= f.label :content, class: "form-label"%>
      <span class="badge bg-danger">必須</span>
      <button type="button" id="experience-template-button" class="btn btn-info btn-sm">記入例</button>
      <div id="content-output" contenteditable="true" class="form-control <%= "is-invalid" if experience.errors.include?(:content) %>" style="min-height: 135px;"
        data-farmer-name="<%= current_user.farmer.name %>"
        data-farmer-address="<%= current_user.farmer.address %>"
        data-farmer-product="<%= current_user.farmer.product %>">
      </div>
    <%= f.hidden_field :content, id: "hidden-content" %>
  </div>

  <div class="mb-3">
    <%= f.label :images, class: "form-label" %>
    <span class="badge bg-secondary">任意</span>
    <%= f.file_field :images, multiple: true, class: "form-control" %>
  </div>

  <div class="mb-4">
    <%= f.submit class: "btn btn-primary w-100" %>
  </div>
<% end %>

app/views/experiences/edit.html.erb
<div class="container experience-container">
  <h2 class="text-center mb-4">体験情報編集</h2>

  <%= render 'form', experience: @experience %>

  <div class="text-center">
    <%= link_to "戻る", experiences_path %>
  </div>
</div>

app/views/experiences/index.html.erb
<div class="container experience-container">
  <h2 class="text-center mb-4">体験情報一覧</h2>


  <%= link_to "体験情報を登録する", new_experience_path, class: "btn btn-primary btn-lg mb-4" %>

  <% @experiences.each do |experience| %>
    <div class="card mb-4">
      <div class="card-body">
        <% experience.plots.each do |plot| %>
          <span class="badge bg-info fs-5 mb-3"><%= plot.name %></span>
        <% end %> 
        
        <h5 class="card-title">
          <%= link_to experience.title, experience_path(experience), class: "text-decoration-none" %>
        </h5>
        <p class="card-text rows5"><%= simple_format(truncate(experience.content, length: 300))  %></p>
        
        <% experience.images.each do |image| %>
          <%= image_tag(image, alt: "体験情報画像", class: "img-fluid mb-2", style: "max-width: 24%;") %>
        <% end %>
        <div class="d-flex">

          <%= link_to "カレンダー登録", experience_path(experience, anchor: "detail_section"), class: "btn btn-outline-primary me-2" %>
          <%= link_to "詳細", experience_path(experience), class: "btn btn-outline-secondary me-2" %>
          <%= link_to "編集", edit_experience_path(experience), class: "btn btn-secondary me-2" %>
          <%= link_to "削除", experience_path(experience), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  <% end %>
  
   <div class="text-center">
    <%= link_to "戻る", farmers_path %>
  </div>
</div>

app/views/experiences/new.html.erb
<div class="container experience-container">
  <h2 class="text-center mb-4">体験情報登録</h2>

  <%= render 'form', experience: @experience %>

  <div class="text-center">
    <%= link_to "戻る", experiences_path %>
  </div>
</div>

app/views/experiences/show.html.erb
<div class="container experience-container">
  <h2 class="text-center mb-4"><%= @experience.title %></h2>

  <div class="d-flex justify-content-end">
    <%= render 'users/follow_form', user: @experience.farmer.user %>
    <%= render 'users/conversation_form', user: @experience.farmer.user %>
  </div>

  <% @plots.each do |plot| %>
    <span class="badge bg-info fs-5 mb-3"><%= plot.name %></span>
  <% end %> 
    
  <div class="mb-3">
    <h5><%= @experience.title %></h5>
  </div>

  <div class="my-3">
    <%= simple_format(@experience.content) %>
  </div>

  <% if @experience.images.attached? %>
    <% @experience.images.each do |image| %>
      <%= image_tag(image, alt: "体験情報画像", class: "img-fluid mb-2 ms-2", style: "max-width: 24%;") %>
    <% end %>
  <% end %>

  <hr id="detail_section">
  <h2 class="text-center mb-4">農業体験カレンダー</h2>

  <%= month_calendar events: @experience.schedules.saved do |date, schedules| %>
    <%= date.strftime("%-d") %>
    <% schedules.each do |schedule| %>
      <div>
        <p><%= schedule.title %></p>
        <%= schedule.start_time.strftime("%H:%M") %> - <%= schedule.end_time.strftime("%H:%M") %>
        <% if current_user == @experience.farmer.user %>
          <%= link_to "編集", edit_experience_schedule_path(@experience, schedule), class: "btn btn-outline-primary btn-sm" %>
          <%= link_to "削除", experience_schedule_path(@experience, schedule), method: :delete, class: "btn btn-outline-danger btn-sm" %>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <% if current_user == @experience.farmer.user %>
    <%= form_with(model: [@experience, @experience.schedules.build], local: true) do |f| %>
      <% if @schedule.present? && @schedule.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <ul>
          <% @schedule.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-3">
        <%= f.label :title, "タイトル"%>
        <span class="badge bg-danger">必須</span>
        <%= f.text_field :title, placeholder: "農業体験の内容を記入してください（15字以内）", class: "form-control w-25" %>
      </div>

      <div class="mb-3">
        <%= f.label :start_time, "開始時刻" %>
        <%= f.datetime_select :start_time %>
      </div>
      
      <div class="mb-3">
        <%= f.label :end_time, "終了時刻" %>
        <%= f.datetime_select :end_time %>
      </div>

      <div class="mb-3">
        <%= f.submit "スケジュールを追加", class: "btn btn-primary" %>
      </div>
    <% end %>
  <% end %>

  <div class="text-center">
    <% if current_user == @experience.farmer.user %>
      <%= link_to "体験情報一覧へ", experiences_path %>
    <% else %>
      <%= link_to "戻る", overview_farmer_path(@experience.farmer) %>
    <% end %> 
  </div>
</div>