config/routes.rb
Rails.application.routes.draw do
  get 'tops/index'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
    post 'users/guest_farmer_nil_sign_in', to: 'users/sessions#guest_farmer_nil_sign_in'
    post 'users/guest_farmer_present_sign_in', to: 'users/sessions#guest_farmer_present_sign_in'
    post 'users/guest_general_nil_sign_in', to: 'users/sessions#guest_general_nil_sign_in'
    post 'users/guest_general_present_sign_in', to: 'users/sessions#guest_general_present_sign_in'
  end

  root 'tops#index'
  resources :tops, only: [:index]
  resources :users, only: [:show, :index]
  resources :relationships, only: [:create, :destroy]
  resources :users, only: [:show] do
    get "follows", on: :member
  end

  resources :generals, only: [:new, :create, :show, :edit, :update]
  resources :farmers, only: [:index, :new, :create, :show, :edit, :update] do
    get "overview", on: :member
  end
  resources :posts
  resources :experiences do
    resources :schedules, only: [:create, :edit, :update, :destroy]
  end
  resources :conversations do
    resources :messages
  end
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :farmer
  has_many_attached :images

  validates :title, presence: true, length: { maximum: 255 }
  validate :validate_images

  scope :created_at_sorted, -> { order(created_at: :desc) }

  def validate_images
    if images.attached? && images.length > 4
      errors.add(:images, 'は最大4枚までアップロードできます。')
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :set_post, only: [:show, :edit, :update, :destroy]
 
  def index
    @posts = current_user.farmer.posts.created_at_sorted
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.farmer.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: "投稿が保存されました。"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "投稿が更新されました。"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: "投稿が削除されました。"
  end

  
  private

  def post_params
    params.require(:post).permit(:title, :content, images: [])
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :title, class: "form-label"%>
    <span class="badge bg-danger">必須</span>
    <%= f.text_field :title, class: "form-control#{" is-invalid" if post.errors.include?(:title)}", placeholder: "タイトルを入力してください" %>
  </div>

  <div class="mb-3">
    <%= f.label :content, class: "form-label"%>
    <span class="badge bg-secondary">任意</span>
    <%= f.text_area :content, class: "form-control", placeholder: "内容を入力してください", rows: 12 %>
  </div>

  <div class="mb-3">
    <%= f.label :images, class: "form-label" %>
    <span class="badge bg-secondary">任意</span>
    <%= f.file_field :images, multiple: true, class: "form-control" %>
  </div>

  <div class="mb-4">
    <%= f.submit class: "btn btn-primary w-100" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <h2 class="text-center mb-4">投稿編集</h2>

  <%= render 'form', post: @post %>

  <div class="text-center">
    <%= link_to "戻る", posts_path %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container post-container">
  <h2 class="text-center mb-4">投稿一覧</h2>

  <%= link_to "投稿する", new_post_path, class: "btn btn-primary btn-lg mb-4" %>

  <% @posts.each do |post| %>
    <div class="card mb-4">
      <div class="card-body">
        <p class="card-text date"><%= post.created_at.strftime("%Y年%m月%d日") %></p>
        <h5 class="card-title">
          <%= link_to post.title, post_path(post), class: "text-decoration-none" %>
        </h5>
        <p class="card-text rows5"><%= simple_format(truncate(post.content, length: 200))  %></p>

        <% post.images.each do |image| %>
          <%= image_tag(image, alt: " 投稿画像", class: "img-fluid mb-2", style: "max-width: 23%;") %>
        <% end %>

        <div class="d-flex">
          <%= link_to "詳細", post_path(post), class: "btn btn-outline-secondary me-2" %>
          <%= link_to "編集", edit_post_path(post), class: "btn btn-secondary me-2" %>
          <%= link_to "削除", post_path(post), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  <% end %>

   <div class="text-center">
    <%= link_to "戻る", farmers_path %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h2 class="text-center mb-4">新規投稿</h2>

  <%= render 'form', post: @post %>

  <div class="text-center">
    <%= link_to "戻る", posts_path %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <h2 class="text-center mb-4">投稿</h2>

  <div class="d-flex justify-content-end">
    <%= render 'users/follow_form', user: @post.farmer.user %>
    <%= render 'users/conversation_form', user: @post.farmer.user %>
  </div>

  <div class="mb-3 border-bottom">
    <div class="col">
      <h4 class="mb-0"><%= @post.title %></h4>
    </div>
  </div>

  <div class="mb-3">
    <div class="col">
      <%= simple_format(@post.content) %>
    </div>
  </div>

  <% if @post.images.attached? %>
    <% @post.images.each do |image| %>
      <%= image_tag(image, alt: "投稿画像", class: "img-fluid mb-2") %>
    <% end %>
  <% end %>
  
  <div class="text-center">
    <% if current_user == @post.farmer.user %>
      <%= link_to "投稿一覧へ", posts_path %>
    <% else %>
      <%= link_to "戻る", overview_farmer_path(@post.farmer) %>
    <% end %> 
  </div>
</div>