config/routes.rb
Rails.application.routes.draw do
  get 'tops/index'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
    post 'users/guest_farmer_nil_sign_in', to: 'users/sessions#guest_farmer_nil_sign_in'
    post 'users/guest_farmer_present_sign_in', to: 'users/sessions#guest_farmer_present_sign_in'
    post 'users/guest_general_nil_sign_in', to: 'users/sessions#guest_general_nil_sign_in'
    post 'users/guest_general_present_sign_in', to: 'users/sessions#guest_general_present_sign_in'
  end

  root 'tops#index'
  resources :tops, only: [:index]
  resources :users, only: [:show, :index]
  resources :relationships, only: [:create, :destroy]
  resources :users, only: [:show] do
    get "follows", on: :member
  end

  resources :generals, only: [:new, :create, :show, :edit, :update]
  resources :farmers, only: [:index, :new, :create, :show, :edit, :update] do
    get "overview", on: :member
  end
  resources :posts
  resources :experiences do
    resources :schedules, only: [:create, :edit, :update, :destroy]
  end
  resources :conversations do
    resources :messages
  end
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Farm Link</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark">  
        <%= link_to "Farm Link", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "農家を探す", farmers_path, class: "nav-link" %>
            </li>
            <% if user_signed_in? %>
              <% if current_user.role == "general" %>
                <% if current_user.general&.persisted? %>
                  <li class="nav-item dropdown">
                    <%= link_to "マイページ", "#", class: "nav-link dropdown-toggle", id: "navbarDropdown", role: "button", data: { bs_toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" } %>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <%= link_to "アカウント情報", user_path(current_user), class: "dropdown-item" %>
                      <%= link_to "プロフィール", general_path(current_user.general), class: "dropdown-item" %>
                      <%= link_to "お気に入り一覧", follows_user_path(current_user), class: "dropdown-item" %>
                      <%= link_to "メッセージ一覧", conversations_path, class: "dropdown-item" %>
                    </div>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to "プロフィール作成", new_general_path, class: "nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "アカウント情報", user_path(current_user), class: "nav-link" %>
                  </li>                              
                <% end %>
              <% elsif current_user.role == "farmer" %>
                <% if current_user.farmer&.persisted? %>
                  <li class="nav-item">
                    <%= link_to "体験情報ページ", experiences_path, class: "nav-link" %>
                  </li> 
                  <li class="nav-item">
                    <%= link_to "投稿ページ", posts_path, class: "nav-link" %>
                  </li>                                                          
                  <li class="nav-item dropdown">
                    <%= link_to "マイページ", "#", class: "nav-link dropdown-toggle", id: "navbarDropdown", role: "button", data: { bs_toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" } %>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <%= link_to "アカウント情報", user_path(current_user), class: "dropdown-item" %>
                      <%= link_to "プロフィール", farmer_path(current_user.farmer), class: "dropdown-item" %>
                      <%= link_to "お気に入り一覧", follows_user_path(current_user), class: "dropdown-item" %>
                      <%= link_to "メッセージ一覧", conversations_path, class: "dropdown-item" %>
                      <%= link_to "紹介ページ", overview_farmer_path(current_user.farmer), class: "dropdown-item" %>
                    </div>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to "プロフィール作成", new_farmer_path, class: "nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "アカウント情報", user_path(current_user), class: "nav-link" %>
                  </li>                              
                <% end %>
              <% end %>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "アカウント登録", new_user_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
            <% if current_user&.admin? %>
              <li class="nav-item active">
              <%= link_to '管理者画面', rails_admin_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <% if content_for?(:main_image) %>
      <%= yield(:main_image) %>
    <% end %>

    <main class="container-fluid mt-4">
      <% if notice %>
        <div class="alert alert-info" role="alert">
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger" role="alert">
          <%= alert %>
        </div>
      <% end %>
      <%= yield %>
    </main>

    <footer class="footer mt-auto py-3">
      <span class="footer-text">&copy; <%= Time.current.year %> Farm Link</span>
    </footer>
  </body>
</html>